# Python Chapter_4 Task_2 list

Task 1
Data Cleaning Challenge on Sales Data.

Task 2
Merge Function 1 Example

Task 3
List Comprehension 2 examples

Task 4
Lambda Function 2 examples with Map, Filter, Reduce

# 1. Data Cleaning Challenge on Sales Data.

In [2]:
import pandas as pd
sales_data1 = pd.read_csv("sales_transactions_2017.csv")
sales_data2 = pd.read_csv("sales_transactions_2018.csv")
sales_data3 = pd.read_csv("sales_transactions_2019.csv")

total_sales = pd.concat([sales_data1,sales_data2,sales_data3],ignore_index=True)

total_sales.to_csv("combined_sales.csv",index = False)

In [23]:
#Descirbe to find mean median mode
total_sales.describe()
pd.set_option("display.max_rows",1000)

In [31]:
#info
total_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111206 entries, 0 to 111205
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Date            98615 non-null   object
 1   Voucher         98649 non-null   object
 2   Party           111166 non-null  object
 3   Product         98615 non-null   object
 4   Qty             98649 non-null   object
 5   Rate            98648 non-null   object
 6   Gross           98648 non-null   object
 7   Disc            5597 non-null    object
 8   Voucher Amount  27560 non-null   object
dtypes: object(9)
memory usage: 7.6+ MB

### 1. Find any duplicate observations/rows

In [80]:
#Find duplicate entry
total_sales.duplicated().sum()

np.int64(14582)

### 2. Remove Duplicates

In [81]:
total_sales = total_sales.drop_duplicates()
total_sales.duplicated().sum()

np.int64(0)

### 3. Handle Missing values

In [10]:
total_sales.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

#### 3.1 Fill current date where date cell is nan

In [82]:
#place current date where date cell has nan
total_sales.loc[total_sales["Date"].isna(),"Date"] = "28/07/2026"
total_sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111204,28/07/2026,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,28/07/2026,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

#### 3.2 Write incremented voucher number where voucher cell is nan

In [83]:
# Create a sequence starting at 101 for missing values
start_value = 101
missing_count = total_sales['Voucher'].isna().sum()

# Generate the series
voucher_series = range(start_value, start_value + missing_count)

# Fill NaN with the series
total_sales.loc[total_sales['Voucher'].isna(), 'Voucher'] = list(voucher_series)

total_sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
111204,28/07/2026,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
111205,28/07/2026,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### 3.3 Remove the observations where party or product is having nan as both are categorical data can not define the suitable name

In [84]:
total_sales = total_sales.dropna(subset = ["Party","Product"])
total_sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

### 3.4 Remove observations where Rate is NAN

In [85]:
total_sales.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  1
Gross                 1
Disc              92781
Voucher Amount    70814
dtype: int64

In [86]:
total_sales

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [90]:
total_sales = total_sales.dropna(subset=["Rate"])

In [92]:
total_sales.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  0
Gross                 0
Disc              92780
Voucher Amount    70813
dtype: int64

In [93]:
total_sales.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [95]:
total_sales["Voucher Amount"].isna().sum()

np.int64(70813)

### 4. Change params types from object to float for qty rate and gross, because then can perform the mathematical operation

In [101]:
pd.to_datetime()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
111197,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
111198,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
111199,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
111200,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
111201,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

# Task 2 Merge Function 1 Example

In [9]:
import pandas as pd

df1 = pd.DataFrame({"id": [1, 2, 3], "name": ["Kannan", "Arun", "Priya"]})
df2 = pd.DataFrame({"id": [2, 3, 4], "age": [30, 25, 40]})

merged = pd.merge(df1, df2, on="id")
print(merged)
## whatever id common 2nd datafram columns are merged, even it control further level also
#we can control this with the how parameter:
#how="inner" → only matching IDs (default).
#how="left" → all IDs from df1, match if possible.
#how="right" → all IDs from df2, match if possible.
#how="outer" → all IDs from both, fill missing with NaN.

print("----------------------------------------------------")
mergd2 = pd.merge(df1, df2, on="id", how="outer")
print(mergd2)

   id   name  age
0   2   Arun   30
1   3  Priya   25
----------------------------------------------------
   id    name   age
0   1  Kannan   NaN
1   2    Arun  30.0
2   3   Priya  25.0
3   4     NaN  40.0

# 3. List Comprehension 2 examples

list comprehensions are very handy with pandas too. They’re often used when you want to quickly build a new column or transform data without writing long loops.

### 1. Create a New Column with Transformation

In [12]:
import pandas as pd

df = pd.DataFrame({"name": ["Kannan", "Arun", "Priya"], "age": [25, 30, 28]})

# Add a new column with age doubled
df["double_age"] = [age * 2 for age in df["age"]]

print(df)

     name  age  double_age
0  Kannan   25          50
1    Arun   30          60
2   Priya   28          56

### 2: Conditional Transformation

In [13]:
# Label people as 'Young' if age < 28 else 'Adult'
df["category"] = ["Young" if age < 28 else "Adult" for age in df["age"]]

print(df)

     name  age  double_age category
0  Kannan   25          50    Young
1    Arun   30          60    Adult
2   Priya   28          56    Adult

# 4. Lambda Function 2 examples with Map, Filter, Reduce

In [14]:
# Example 1:
# A lambda that adds 10 to a number
add_ten = lambda x: x + 10

print(add_ten(5))   # 15
print(add_ten(20))  # 30

15
30

In [15]:
#Example 2
import pandas as pd

df = pd.DataFrame({"name": ["Kannan", "Arun", "Priya"], "age": [25, 30, 28]})

# Add 5 years to each age using lambda + apply
df["future_age"] = df["age"].apply(lambda x: x + 5)

print(df)

     name  age  future_age
0  Kannan   25          30
1    Arun   30          35
2   Priya   28          33

In [16]:
#Example 3
# Categorize based on age
df["category"] = df["age"].apply(lambda x: "Young" if x < 28 else "Adult")

print(df)

     name  age  future_age category
0  Kannan   25          30    Young
1    Arun   30          35    Adult
2   Priya   28          33    Adult

In [17]:
#Example 4 with Map and filter
numbers = [1, 2, 3, 4, 5, 6]

# Double each number using map
doubled = list(map(lambda x: x * 2, numbers)) # map applies the lambda to every element.
print("Doubled:", doubled)  # [2, 4, 6, 8, 10, 12]

# Filter even numbers using filter
evens = list(filter(lambda x: x % 2 == 0, numbers)) # filter keeps only those elements where the lambda returns True.
print("Evens:", evens)  # [2, 4, 6]

Doubled: [2, 4, 6, 8, 10, 12]
Evens: [2, 4, 6]

In [18]:
# Example 5 with reduce
from functools import reduce

numbers = [1, 2, 3, 4, 5]

# Sum of all numbers using reduce
total = reduce(lambda x, y: x + y, numbers)
print("Sum:", total)  # 15

# Product of all numbers using reduce
product = reduce(lambda x, y: x * y, numbers)
print("Product:", product)  # 120

Sum: 15
Product: 120