# Program List
1.	Write a program to take a name and age from the user and print a greeting message.
2.	Create a list of numbers and print only even numbers using a for loop.
3.	Write a program that handles division by zero using try-except.
4.	Given a string, count how many vowels it has.
5.	Reverse a list without using built-in functions.
6.	Create a dictionary with at least 5 key-value pairs and print them.
7.	Write a Pandas code to read a CSV and print the top 5 rows.
8.	Create a DataFrame from a Python dictionary.
9.	Replace all missing values in a DataFrame with the column’s mean.
10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

#### 1. Write a program to take a name and age from the user and print a greeting message.

In [1]:
userName = input("Enter your name : ")
age = input("Enter your age : ")
print("Hello,",userName,"aged", age, "Welcome to Star Health Insurance policy")

Enter your name :  Kannan
Enter your age :  26

Hello Kannan aged 26 Welcome to Star Health Insurance policy

### 2. Create a list of numbers and print only even numbers using a for loop.

In [5]:
list = range(1,10)
for i in list:
    if i % 2==0:
        print(i)

2
4
6
8

### 3. Write a program that handles division by zero using try-except.

In [10]:
while True:
    try:
        quotient = float(input("Enter a quotient : "))
        denometer = float(input("Enter a denometer: "))
       
        result = quotient/denometer
        print("Answer:",result)
        break;
    
    except ValueError as e:
        print("You entered invalid number, Please try again")
    except ZeroDivisionError as e:
        print("Quotient can not be divided by zero Denometer")

Enter a quotient :  34s

You entered invalid number, Please try again

Enter a quotient :  56
Enter a denometer:  4dd

You entered invalid number, Please try again

Enter a quotient :  34
Enter a denometer:  0

Quotient can not be divided by zero Denometer

Enter a quotient :  34
Enter a denometer:  8

Answer: 4.25

### 4.Given a string, count how many vowels it has.

In [18]:
input_text = input("Enter a String")
vowels = set()
for c in input_text:
    if c in "aeiou":
        vowels.add(c)
print("In the enterted string -->",input_text,"and Vowels are",vowels)

Enter a String Gen AI Program

In the enterted string --> Gen AI Program and Vowels are {'e', 'o', 'a'}

### 5. Reverse a list without using built-in functions.

In [74]:
fruit_list = ["Apple","Mangao","Banana","Orange"]
list_len = len(fruit_list)
iterate = int(list_len/2)

for i in range(iterate):
     temp = fruit_list[i]
     fruit_list[i] = fruit_list[(list_len-i)-(list_len+1)] ## Acces last element using negative index
     fruit_list[(list_len-i)-(list_len+1)]  = temp
print(fruit_list)

['Orange', 'Banana', 'Mangao', 'Apple']

#### 6. Create a dictionary with at least 5 key-value pairs and print them.

In [72]:
# Example dictionary with 5 key-value pairs
student = {
    "name": "Kannan",
    "age": 25,
    "degree": "M.Tech",
    "score": 90,
    "city": "Sivakasi"
}

print(student)

{'name': 'Kannan', 'age': 25, 'degree': 'M.Tech', 'score': 90, 'city': 'Sivakasi'}

### 6. Write a Pandas code to read a CSV and print the top 5 rows.

In [121]:
import pandas as pd
in_patient_dtls = pd.read_csv("patient_registration.csv")
in_patient_dtls.head()

      name   age location
0     John   NaN  Madurai
1   Mahesh  23.0  chennai
2    Ameer  29.0  chennai
3      Anu   NaN  chennai
4  Prakesh  34.0  chennai

### 8. Create a DataFrame from a Python dictionary.

In [80]:
# Dictionary with lists as values
data = {
    "Name": ["Aparna", "Pankaj", "Sudhir", "Geeku"],
    "Degree": ["MBA", "BCA", "M.Tech", "MBA"],
    "Score": [90, 40, 80, 98]
}

# Create DataFrame
df = pd.DataFrame(data)

print(df)

     Name  Degree  Score
0  Aparna     MBA     90
1  Pankaj     BCA     40
2  Sudhir  M.Tech     80
3   Geeku     MBA     98

### 9. Replace all missing values in a DataFrame with the column’s mean.

In [122]:
##in_patient_dtls.fillna()
print("Before handling missing values\n")
print(in_patient_dtls)
print("\nAfter handling missing values\n ")
in_patient_dtls["age"] = in_patient_dtls["age"].fillna(value = in_patient_dtls["age"].mean())
print(in_patient_dtls)

Before handling missing values

      name   age location
0     John   NaN  Madurai
1   Mahesh  23.0  chennai
2    Ameer  29.0  chennai
3      Anu   NaN  chennai
4  Prakesh  34.0  chennai
5    Solai  56.0  chennai

After handling missing values

      name   age location
0     John  35.5  Madurai
1   Mahesh  23.0  chennai
2    Ameer  29.0  chennai
3      Anu  35.5  chennai
4  Prakesh  34.0  chennai
5    Solai  56.0  chennai

### 10. Filter rows in a DataFrame where the "Age" column is greater than 30.

In [123]:
print(in_patient_dtls)
print("\nBelow detatils are filtering patient greater than 30")
in_patient_dtls[in_patient_dtls["age"]>30]

      name   age location
0     John  35.5  Madurai
1   Mahesh  23.0  chennai
2    Ameer  29.0  chennai
3      Anu  35.5  chennai
4  Prakesh  34.0  chennai
5    Solai  56.0  chennai

Below detatils are filtering patient greater than 30

      name   age location
0     John  35.5  Madurai
3      Anu  35.5  chennai
4  Prakesh  34.0  chennai
5    Solai  56.0  chennai