# Pandas Data Structure
##### * One dimensional
##### * Two Dimensional
##### * Filtering & Selection & Sorting
##### * Handling Missing Data

In [5]:
import pandas as pd
pd.Series(data = [1,2,3,0.7])
data = {"name":["A","B"],"age":[34,56]}
data = [{"name":"kannan","age":23},{"name":"ABC","age":34}]
data_1 = pd.DataFrame(data)

In [23]:
data_1.sort_values(by="name")

     name  age
1     ABC   34
0  kannan   23

In [26]:
#euro_match = pd.read_csv("football_team.csv",index_col="Team") this is used to put our own rather default index 0 , 1, 2  
euro_match = pd.read_csv("football_team.csv")
euro_match

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [28]:
pd.set_option('display.max_columns', None)
euro_match

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

# Data filtering and data frame functions

In [38]:
#Data filtering
red_card_teams = filtered_data[filtered_data["Red Cards"] > 0]

print(red_card_teams)

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

In [34]:
filtered_data.dtypes

Team            object
Goals            int64
Yellow Cards     int64
Red Cards        int64
dtype: object

### Employee details handling missing data

In [ ]:
employee = pd.read_csv("employee.csv")

In [41]:
#it will return where nan is exist rest FASE
#isnotnull is opposite to isnull
employee.isnull()

    Name    Age  Department  Salary  Join_Date
0  False  False       False   False      False
1  False  False       False    True      False
2  False   True       False   False      False
3  False  False       False   False      False
4  False  False       False   False      False
5  False  False       False   False      False
6   True  False       False   False      False
7  False  False       False    True      False

In [42]:
employee.isnull().sum()

Name          1
Age           1
Department    0
Salary        2
Join_Date     0
dtype: int64

In [43]:
employee

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [12]:
#Remove Duplicates
employee.drop_duplicates(subset=["Name"],inplace=True)
#pd.set_option("display.max_rows", None)
employee

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

### Update value in pandas dataframe using .loc[]

In [54]:
#wherever salary has nan put 60000 if the age is 31 in IT Tech
employee[(employee["Department"]=='IT Tech') & (employee["Age"]==31.0)]
employee.loc[(employee["Department"].isin(["IT", "Tech"])) & (employee["Age"]==31.0),"Salary"] = 60000
employee

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  60000.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [69]:
#Select multiple column
employee[["Name","Age"]]

      Name   Age
0   Rajesh  29.0
1    Nasir  31.0
2  Mathiew   NaN
3  Gilbert  29.0
4    Kevin  28.0
5    Navin  35.0
6      NaN  40.0

In [80]:
#indexing row and col
d = employee.loc[[0,1]]["Name"]
print(d)

0    Rajesh
1     Nasir
Name: Name, dtype: object

In [84]:
#index row and col using iloc
d = employee.iloc[0]["Name"]
print(d)

Rajesh

In [86]:
#fillna - PUT 0 whereeer nan is exist
employee.fillna("NA")

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  60000.0  12-11-2020
2  Mathiew    NA    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6       NA  40.0         IT  64000.0  10-09-2022

In [87]:
#Dropna
employee.dropna()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  60000.0  12-11-2020
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [90]:
# Iterate rows
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
df = pd.DataFrame(dict)

for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object

In [92]:
employee.loc[[0,1],"Salary"]

0    60000.0
1    60000.0
Name: Salary, dtype: float64

In [99]:
#Iterating columnwise
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
  
df = pd.DataFrame(dict)
 
print(df)
#columns = list(df)
 
#for i in columns:
 #   print (df[i][2])

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [106]:
#insert
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df.insert(2, 'C', [5, 6])

print(df)

   A  B  C
0  1  3  5
1  2  4  6

In [108]:
#unique
employee["Age"]

0    29.0
1    31.0
2     NaN
3    29.0
4    28.0
5    35.0
6    40.0
Name: Age, dtype: float64

In [111]:
#nunique - it tells how unique column or row in a give datafrom , by default column
employee.nunique(axis = 1)

0    5
1    5
2    4
3    5
4    5
5    5
6    4
dtype: int64

In [114]:
#count unique value in columns
# Count unique values in the 'Name' column
employee['Name'].nunique()

6

In [115]:
#value counts, while group by count the value
employee.groupby('Age')['Name'].value_counts()

Age   Name
28.0  Kevin      1
29.0  Gilbert    1
      Rajesh     1
31.0  Nasir      1
35.0  Navin      1
Name: count, dtype: int64

In [116]:
#Column attribute returns the column name
df = pd.DataFrame({
    "A": [12, 4, 5, None, 1],
    "B": [7, 2, 54, 3, None],
    "C": [20, 16, 11, 3, 8],
    "D": [14, 3, None, 2, 6] })

idx = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']
df.index = idx

res = df.columns

print("\n Name of Columns of Pandas DataFrame")
print(res)

 Name of Columns of Pandas DataFrame
Index(['A', 'B', 'C', 'D'], dtype='object')

In [117]:
#astype
df = pd.DataFrame({'A': ['1', '2'], 'B': ['3.5', '4.5']})

res = df.astype({'A': int, 'B': float})
print(res)
print(res.dtypes)

   A    B
0  1  3.5
1  2  4.5
A      int64
B    float64
dtype: object

In [124]:
#Drop
employee.drop(1)

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [125]:
#To drop column
employee.drop("Name",axis=1)

    Age Department   Salary   Join_Date
0  29.0        Ops  60000.0  21-05-2023
1  31.0    IT Tech  60000.0  12-11-2020
2   NaN    Support  58000.0  15-01-2025
3  29.0        Ops  60000.0  21-05-2021
4  28.0    Support  61000.0  30-07-2024
5  35.0    Support  72000.0  19-08-2023
6  40.0         IT  64000.0  10-09-2022

In [138]:
#nlargest - may be used nth highest value, Simlarly for nsmallest
employee.nlargest(7,"Salary").sort_values("Salary",ascending=True).head(1)

      Name  Age Department   Salary   Join_Date
2  Mathiew  NaN    Support  58000.0  15-01-2025