# 1. Create 3 Data Frames using Dictionaries

### Pandas allows us to create a DataFrame from many data sources. We can create DataFrames directly from Python objects like lists and dictionaries or by reading data from external files like CSV, Excel or SQL databases.

In [2]:
#Ex1
import pandas as pd
 
lst = ['Geeks', 'For', 'Geeks', 'is', 
            'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [18]:
#Ex2
import pandas as pd
 
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
df = pd.DataFrame(data)
 
df

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

##### The indexing operator [] is the basic way to select data in Pandas. We can use this operator to access columns from a DataFrame. This method allows us to retrieve one or more columns.

In [30]:
#Ex3
import pandas as pd

#Read data from CSV and convert to dataframe, if we mentiont the index column , then that react as index column instead default  0,1,2,2
#With out index
data = pd.read_csv("sample.csv") 
print(data)
print("--------------------------------------------")
#With index
data = pd.read_csv("sample.csv",index_col = "name") 
data

     name  age location
0    John   20  Madurai
1  Mahesh   23  chennai
--------------------------------------------

        age location
name
John     20  Madurai
Mahesh   23  chennai

In [33]:
#Ex5
import pandas as pd
 
data = pd.read_csv("sample.csv", index_col ="name")

first = data.loc["John"] # It will fetch only john's detail
print(first)

second = data.iloc[1] # It will fetch data based on index, here it is fetching 2nd index row
second

age              20
location    Madurai
Name: John, dtype: object

age              23
location    chennai
Name: Mahesh, dtype: object